### PR TITLE
[FIX] MagneticFieldStrength should be float

### PR DESCRIPTION
**Pull request by oesteban**

### CODE REVIEW

**Comment by chrisgorgo** [comment]
@rwblair could you deploy? Thanks!

**Comment by oesteban** [comment]
We should also correct old entries, right? This should minimize errors:
- s/1/1.5/g
- s/2/2.95/g

(we will probably push some 1T to 1.5T, but I'd say most of the records are 1.5T)

**Comment by chrisgorgo** [comment]
This would better be done in data cleaning: https://www.kaggle.com/chrisfilo/mriqc-data-cleaning

**Comment by rwblair** [comment]
@chrisfilo sorry for the delay, latest master should be up now on the server.

**Comment by chrisgorgo** [comment]
Thanks!

Best,
Chris

**Pull request merged**
