### PR TITLE
FIX: Use eve_swagger.get_swagger_blueprint

### PR DESCRIPTION
**Pull request by effigies**
Testing that CI is broken before trying to fix.

### CODE REVIEW

**Comment by effigies** [comment]
Not sure who's running this these days. @rwblair?

**Comment by effigies** [comment]
Seems to work: https://github.com/poldracklab/mriqc/pull/862 is no longer failing on the API submission, though it is failing for other reasons.

**Comment by rwblair** [comment]
Yeah I administer it. Thanks for finding a fix for the eve api change.

**Comment by effigies** [comment]
Do we need to tag a release? I can do it if it would be helpful, just don't want to preempt the usual way of things.

**Pull request merged**
