### PR TITLE
Allow api to take user report feedback

### PR DESCRIPTION
**Pull request by rwblair**
Opening this up for discussion.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
Wouldn't it make more sense for the ratings to be a sub dictionary of `settings['DOMAIN']['bold/T1w/T2w']['schema']`?

**Comment by oesteban** [comment]
How's the state of affairs here?

**Comment by rwblair** [comment]
There is nothing in the bold/t1w schemas that call for unique values in the api except for the id generated by the api on entry creation.

Right now the user ratings are based on input files md5sums. This means that there might be multiple runs of mriqc on the same images, which leads to multiple entries in the api for the same input files. To get a user(s) ratings for the specific entry in the api that was generated from their run would require getting the api id generated when the iqms measures are submitted in mriqc and then passing that value down through mriqc into report generation so the report javascript knows where to put the information.

To keep aggregating rating counts simple I was having all of the ratings be dropped into one high level schema. The thinking was that the rating was of the input image and its usability,  but its just as much a rating of the values being shown in the report as it is of the input image itself.

To tie to specific ratings to specific runs of mriqc I'll see about implementing that second paragraph in my mriqc pr.

**Comment by chrisgorgo** [comment]
Reports will change from version to version - it would me more future proof to tie the ratings to lower level entries.

**Comment by oesteban** [comment]
Resurrecting this: @rwblair do you think we can add some tests to the rating feedback?

**Comment by oesteban** [comment]
Okay, now tests are passing. @rwblair do you think you'd have some bandwidth to add a couple of tests for this new feature?

**Comment by rwblair** [comment]
Have a few things I need to finish up, but if its just adding the properly formatted test data and adding the test function I should be able to do it.

**Pull request merged**
