### PR TITLE
[FIX] Do not pin versions

### PR DESCRIPTION
**Pull request by oesteban**
Automatically upgrade to avoid using versions with known vulnerabilities

### CODE REVIEW

**Comment by oesteban** [comment]
@rwblair something is wrong over here, could you give it a quick eye?

**Comment by oesteban** [comment]
@rwblair 

(just triggering another notification :) )

**Comment by rwblair** [comment]
Looks good. Hard to imagine these 3 packages ever having version conflicts.

**Comment by rwblair** [comment]
Though the tests failing isn't a good sign.

**Pull request merged**
