### PR TITLE
Add goverment shutdown notice

### PR DESCRIPTION
**Pull request by Shotgunosine**
We've got to add language about the shutdown to all external facing government websites. There isn't actually any change in the functional status of the webpage, but we've got to have the language there. Please merge this in when you get a chance.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
Do we still need to merge it or was the situation resolved?

**Comment by vsoch** [comment]
You could change it to more of an "if" clause, like "in the case of..." and then you don't have to jump back and forth @chrisfilo as long as the oompa loompa is around, I think we will continue to have a "situation..." :tangerine:

**Comment by Shotgunosine** [comment]
Situation is resolved, unfortunately, the language for the notice is not something we can change without approval. We could add an environment variable and rebuild when there’s a shutdown. Should I submit a PR with that added?

**Comment by chrisgorgo** [comment]
Sounds like a plan. This could be implemented in the current PR. Thanks!

Best,
Chris

**Comment by Shotgunosine** [comment]
Even better would be to drop in some javascript to pull the operating
status from the Office of Personnel Management's JSON API
<https://www.opm.gov/developer/documentation/current-status-api/> and look
for the phrase "lapse in appropriations". In the last two shutdowns, that
phrase was used in the StatusSummary field. I'll try to get that
implemented this week.

**Comment by chrisgorgo** [comment]
Me might be overengineering a solution for an event that happens once in 4
years :)

Best,
Chris

**Comment by Shotgunosine** [comment]
Might happen again in 3 weeks though.

**Comment by oesteban** [comment]
I guess we will finally need to get this merged, DYT?

EDIT: luckily it took some 50 weeks

**Comment by Shotgunosine** [comment]
Nah, we're funded, it's only a partial shutdown. :)

**Comment by vsoch** [comment]
Only partial? Hmm. Ctrl+Z?

image

**Pull request merged**
