### PR TITLE
Adding endpoint for Nipype telemetry

### PR DESCRIPTION
**Pull request by chrisgorgo**
Example payload
```
{  
   "interface_class_name":"nipype.interfaces.fsl.preprocess.BET",
   "version":"5.0.9",
   "duration_sec":5.033582,
   "mem_peak_gb":0.00703125,
   "inputs":{  
      "in_file":{  
         "shape":[  
            256,
            156,
            256
         ],
         "dtype":"float32",
         "st_size":8677710,
         "ext":".nii.gz"
      },
      "output_type":"NIFTI_GZ",
      "environ":{  
         "FSLOUTPUTTYPE":"NIFTI_GZ"
      }
   }
}
```

### CODE REVIEW

**Comment by chrisgorgo** [comment]
@satra let me know what do you think

**Comment by satra** [comment]
@chrisfilo - seems reasonable as a starting point. it may be useful to have which flags were defined (without necessarily reporting their values). that way no identifiable information can be sent.

**Comment by chrisgorgo** [comment]
What do you mean by flags? inputs?

**Comment by satra** [comment]
which input keys were enabled (had non undefined values) in the input dictionary

**Comment by chrisgorgo** [comment]
Hmm - it will be hard to fit predictive models of memory usage using only such information. Let's discuss tomorrow.

**Comment by vsoch** [comment]
Would you want something sort of agnostic to the specific attributes of any workflow, meaning that it creates a list of attributes with key value pairs (that is always parseable without knowing keys in advance?) Or what about using one of the GA4GH API standards? For example, the cloud workflow might be a good starting point: https://github.com/ga4gh/task-execution-schemas. If that doesn't fit the starting point of my search was their "workstreams page," https://www.ga4gh.org/how-we-work/workstreams/ and from the cloud group there is a whole list to investigate --> https://github.com/ga4gh/wiki/wiki

**Comment by oesteban** [comment]
I would leave the environment variables out (or filter them with a white list). Otherwise people may have passwords and authorization tokens defined and those would get leaked to the API.

**Comment by chrisgorgo** [comment]
Those are not all environment variables present, but only those that are overridden by this particular interface (as in passed as `environ` input).

I also discussed this further with @satra and we decided to replace all non-filepath strings with their md5 hashes. Strings that are file paths will be replaced with their metadata. This should minimize any PHI information leaking.

**Pull request merged**
